export const ADMIN_SETTINGS_ERROR_CODES = {
    SYSTEM_NAME_LENGTH: 'ERR_SYSTEM_NAME_LENGTH',
    SYSTEM_DESCRIPTION_LENGTH: 'ERR_SYSTEM_DESCRIPTION_LENGTH',
    AI_MODEL_INVALID: 'ERR_AI_MODEL_INVALID',
    DEFAULT_EXAM_DURATION_RANGE: 'ERR_DEFAULTEXAMDURATION_RANGE',
    MAX_QUESTIONS_PER_EXAM_RANGE: 'ERR_MAXQUESTIONSPEREXAM_RANGE',
    MAX_AI_REQUESTS_PER_DAY_RANGE: 'ERR_MAXAIREQUESTSPERDAY_RANGE',
    PASSWORD_MIN_LENGTH_RANGE: 'ERR_PASSWORDMINLENGTH_RANGE',
    SESSION_TIMEOUT_RANGE: 'ERR_SESSIONTIMEOUT_RANGE'
};
